### ISSUE TITLE
Implement Location Services 

### ISSUE THREAD

**Issue by Linz413** [MuffinDreamers/MuffinDreamersAndroid#48]
-  Utilize mobile location services

-  Submit a report from the map screen with auto location

**Comment by cartycrabber** [comment]
Implemented location services in commit 4455e07f.  Autofills the text boxes in AddNewRatDataScreen with the current location when the Use Location button is pressed. Also makes sure we have permissions and asks for them if we dont. 

Still need to add ability to submit from map, but that should basically be same thing different page.
